print('Hello, World')
print('Enter your name')
name = input()
print('it is good to meet you ' + name)
print('length of your name is', len(name))
print('Enter your age')
age = input()
print('the person age in this year will be ' + str(int(age) + 1))
# age = int(input()) print('the persons age in this year will be', age + 1)